#pragma once

#include <array>
#include <cstdint>
#include <filesystem>
#include <initializer_list>
#include <string>
#include <string_view>
#include <vector>

namespace holon_npu_tb {

enum class coverage_point : std::uint16_t {
    pe_weight_load,
    pe_masked_weight,
    pe_negative_operands,
    pe_int32_wrap,
    array_shape_1,
    array_shape_16,
    array_shape_mixed_tail,
    axi_lite_aw_w_skew,
    control_done_irq,
    control_error_irq,
    control_soft_reset,
    soft_reset_drain,
    descriptor_valid,
    descriptor_invalid_size,
    descriptor_invalid_version,
    descriptor_invalid_flags,
    descriptor_reserved_nonzero,
    descriptor_address_overflow,
    loader_axi_read_error,
    loader_descriptor_4k_split,
    loader_copy_4k_split,
    isa_class_frontend_control,
    isa_class_predicate,
    isa_class_vector_config,
    isa_class_vector_alu,
    isa_class_vector_memory,
    isa_class_vector_permute,
    isa_class_vector_reduction,
    isa_class_quantization,
    isa_class_matrix,
    isa_class_dma,
    isa_class_csr_debug,
    isa_class_sync,
    isa_class_system,
     frontend_control_movi,
     frontend_control_add,
     frontend_control_addi,
     frontend_control_load,
     frontend_control_store,
     frontend_control_beq,
     frontend_control_bne,
     predicate_ptrue,
     predicate_load,
     vector_config_set,
     vector_load,
     vector_store,
     vector_alu_add,
     vector_alu_sub,
     vector_alu_min,
     vector_alu_max,
     vector_alu_eq,
     vector_alu_lt,
     vector_alu_shl,
     vector_alu_srl,
     vector_alu_sra,
     vector_alu_select,
     vector_permute_gather,
     vector_permute_zip_lo,
     vector_permute_zip_hi,
     vector_permute_unzip_even,
     vector_permute_unzip_odd,
     vector_permute_transpose4,
     vector_reduce_sum,
     vector_reduce_min,
     vector_reduce_max,
     quantization_requantize,
     matrix_gemm_program,
     csr_debug_read,
     frontend_system_fault,
     system_fault_reserved_illegal,
     loader_program_image_copy,
     loader_argument_copy,
     loader_zero_argument_skip,
     control_loader_integration,
     program_flag_semantics,
     local_memory_program_read,
     local_memory_data_read,
     local_memory_bounds_fault,
     local_memory_data_arbiter,
     control_local_memory_integration,
     frontend_system_exit,
     frontend_explicit_fault,
     completion_record_done,
     completion_record_fault,
     completion_record_axi_error,
     completion_record_4k_split,
     frontend_illegal_instruction,
     frontend_scalar_program,
     frontend_scalar_bounds_fault,
     frontend_debug_step,
     frontend_tile_program_done,
     frontend_dma_load_program,
     frontend_dma_store_program,
     frontend_sync_wait_dma,
     frontend_sync_fence_local,
     frontend_sync_fence_dma,
     frontend_vector_program,
     frontend_predicate_program,
     frontend_vector_helper_program,
     frontend_vector_extended_program,
     frontend_quant_program,
     frontend_vector_fault,
     frontend_matrix_program,
     product_top_program,
     product_top_completion_ordering,
     engine_data_arbiter,
     dma_load_success,
     dma_backpressure,
     dma_store_success,
     dma_bounds_fault,
     dma_address_overflow_fault,
     dma_axi_fault,
     dma_store_bresp_fault,
     dma_load_4k_split,
     dma_store_4k_split,
     vector_config,
     vector_load_store,
     vector_alu,
     vector_compare_shift,
     vector_narrow_elements,
     vector_predicate,
     vector_saturating_arithmetic,
     vector_select,
     vector_permute,
     vector_pack_unpack,
     vector_transpose,
     vector_reduction,
     vector_requant,
     vector_faults,
     matrix_engine_clear,
     matrix_engine_accumulate,
     matrix_engine_store,
     matrix_engine_fault,
     matrix_constrained_random,
     matrix_tiled_program,
     vector_constrained_random,
     runtime_examples_rtl,
};

struct coverage_point_info {
    coverage_point point;
    std::string_view name;
    std::string_view description;
};

inline constexpr std::array coverage_registry{
    coverage_point_info{coverage_point::pe_weight_load, "pe_weight_load", "PE B weight load path."},
    coverage_point_info{coverage_point::pe_masked_weight, "pe_masked_weight", "PE masked weight behavior."},
    coverage_point_info{coverage_point::pe_negative_operands, "pe_negative_operands", "Signed negative PE operands."},
    coverage_point_info{coverage_point::pe_int32_wrap, "pe_int32_wrap", "INT32 wraparound arithmetic."},
    coverage_point_info{coverage_point::array_shape_1, "array_shape_1", "1x1x1 array shape."},
    coverage_point_info{coverage_point::array_shape_16, "array_shape_16", "16x16x16 array shape."},
    coverage_point_info{coverage_point::array_shape_mixed_tail, "array_shape_mixed_tail", "Mixed-tail array shape."},
    coverage_point_info{coverage_point::axi_lite_aw_w_skew, "axi_lite_aw_w_skew", "AXI-Lite AW/W channels accepted with independent skew."},
    coverage_point_info{coverage_point::control_done_irq, "control_done_irq", "Successful program completion raises the enabled DONE interrupt."},
    coverage_point_info{coverage_point::control_error_irq, "control_error_irq", "Program or loader fault raises the enabled FAULT interrupt."},
    coverage_point_info{coverage_point::control_soft_reset, "control_soft_reset", "Control-plane software reset path completes."},
    coverage_point_info{coverage_point::soft_reset_drain, "soft_reset_drain", "Software reset waits for accepted transactions to drain before returning to IDLE."},
    coverage_point_info{coverage_point::descriptor_valid, "descriptor_valid", "Valid ABI 3.0 program descriptor is accepted."},
    coverage_point_info{coverage_point::descriptor_invalid_size, "descriptor_invalid_size", "Invalid program descriptor size is rejected."},
    coverage_point_info{coverage_point::descriptor_invalid_version, "descriptor_invalid_version", "Unsupported ABI or ISA version is rejected."},
    coverage_point_info{coverage_point::descriptor_invalid_flags, "descriptor_invalid_flags", "Unknown program descriptor flags are rejected."},
    coverage_point_info{coverage_point::descriptor_reserved_nonzero, "descriptor_reserved_nonzero", "Nonzero reserved descriptor fields are rejected."},
    coverage_point_info{coverage_point::descriptor_address_overflow, "descriptor_address_overflow", "Wrapped descriptor or referenced system address is rejected."},
    coverage_point_info{coverage_point::loader_axi_read_error, "loader_axi_read_error", "Program loader drains and reports an AXI read response error."},
    coverage_point_info{coverage_point::loader_descriptor_4k_split, "loader_descriptor_4k_split", "Descriptor fetch splits at a 4 KiB boundary."},
    coverage_point_info{coverage_point::loader_copy_4k_split, "loader_copy_4k_split", "Program and argument copies split at 4 KiB boundaries."},
    coverage_point_info{coverage_point::isa_class_frontend_control, "isa_class_frontend_control", "Holon frontend-control ISA class executed."},
    coverage_point_info{coverage_point::isa_class_predicate, "isa_class_predicate", "Holon predicate ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_config, "isa_class_vector_config", "Holon vector-config ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_alu, "isa_class_vector_alu", "Holon vector-ALU ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_memory, "isa_class_vector_memory", "Holon vector-memory ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_permute, "isa_class_vector_permute", "Holon vector-permute ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_reduction, "isa_class_vector_reduction", "Holon vector-reduction ISA class executed."},
    coverage_point_info{coverage_point::isa_class_quantization, "isa_class_quantization", "Holon quantization ISA class executed."},
    coverage_point_info{coverage_point::isa_class_matrix, "isa_class_matrix", "Holon matrix ISA class executed."},
    coverage_point_info{coverage_point::isa_class_dma, "isa_class_dma", "Holon DMA ISA class executed."},
    coverage_point_info{coverage_point::isa_class_csr_debug, "isa_class_csr_debug", "Holon CSR/debug ISA class executed."},
    coverage_point_info{coverage_point::isa_class_sync, "isa_class_sync", "Holon synchronization ISA class executed."},
    coverage_point_info{coverage_point::isa_class_system, "isa_class_system", "Holon system ISA class executed."},
    coverage_point_info{coverage_point::frontend_control_movi, "frontend_control_movi", "Frontend movi instruction executed."},
    coverage_point_info{coverage_point::frontend_control_add, "frontend_control_add", "Frontend add instruction executed."},
    coverage_point_info{coverage_point::frontend_control_addi, "frontend_control_addi", "Frontend addi instruction executed."},
    coverage_point_info{coverage_point::frontend_control_load, "frontend_control_load", "Frontend local load instruction executed."},
    coverage_point_info{coverage_point::frontend_control_store, "frontend_control_store", "Frontend local store instruction executed."},
    coverage_point_info{coverage_point::frontend_control_beq, "frontend_control_beq", "Frontend equality branch executed."},
    coverage_point_info{coverage_point::frontend_control_bne, "frontend_control_bne", "Frontend inequality branch executed."},
    coverage_point_info{coverage_point::predicate_ptrue, "predicate_ptrue", "Predicate ptrue instruction executed."},
    coverage_point_info{coverage_point::predicate_load, "predicate_load", "Predicate load instruction executed."},
    coverage_point_info{coverage_point::vector_config_set, "vector_config_set", "Vector configuration instruction executed."},
    coverage_point_info{coverage_point::vector_load, "vector_load", "Vector local load instruction executed."},
    coverage_point_info{coverage_point::vector_store, "vector_store", "Vector local store instruction executed."},
    coverage_point_info{coverage_point::vector_alu_add, "vector_alu_add", "Vector add instruction executed."},
    coverage_point_info{coverage_point::vector_alu_sub, "vector_alu_sub", "Vector subtract instruction executed."},
    coverage_point_info{coverage_point::vector_alu_min, "vector_alu_min", "Vector minimum instruction executed."},
    coverage_point_info{coverage_point::vector_alu_max, "vector_alu_max", "Vector maximum instruction executed."},
    coverage_point_info{coverage_point::vector_alu_eq, "vector_alu_eq", "Vector equality instruction executed."},
    coverage_point_info{coverage_point::vector_alu_lt, "vector_alu_lt", "Vector less-than instruction executed."},
    coverage_point_info{coverage_point::vector_alu_shl, "vector_alu_shl", "Vector shift-left instruction executed."},
    coverage_point_info{coverage_point::vector_alu_srl, "vector_alu_srl", "Vector logical shift-right instruction executed."},
    coverage_point_info{coverage_point::vector_alu_sra, "vector_alu_sra", "Vector arithmetic shift-right instruction executed."},
    coverage_point_info{coverage_point::vector_alu_select, "vector_alu_select", "Vector select instruction executed."},
    coverage_point_info{coverage_point::vector_permute_gather, "vector_permute_gather", "Vector gather instruction executed."},
    coverage_point_info{coverage_point::vector_permute_zip_lo, "vector_permute_zip_lo", "Vector zip.lo instruction executed."},
    coverage_point_info{coverage_point::vector_permute_zip_hi, "vector_permute_zip_hi", "Vector zip.hi instruction executed."},
    coverage_point_info{coverage_point::vector_permute_unzip_even, "vector_permute_unzip_even", "Vector unzip.even instruction executed."},
    coverage_point_info{coverage_point::vector_permute_unzip_odd, "vector_permute_unzip_odd", "Vector unzip.odd instruction executed."},
    coverage_point_info{coverage_point::vector_permute_transpose4, "vector_permute_transpose4", "Vector transpose4 instruction executed."},
    coverage_point_info{coverage_point::vector_reduce_sum, "vector_reduce_sum", "Vector sum reduction executed."},
    coverage_point_info{coverage_point::vector_reduce_min, "vector_reduce_min", "Vector minimum reduction executed."},
    coverage_point_info{coverage_point::vector_reduce_max, "vector_reduce_max", "Vector maximum reduction executed."},
    coverage_point_info{coverage_point::quantization_requantize, "quantization_requantize", "Vector requantization instruction executed."},
    coverage_point_info{coverage_point::matrix_gemm_program, "matrix_gemm_program", "Matrix GEMM tile instruction executed."},
    coverage_point_info{coverage_point::csr_debug_read, "csr_debug_read", "Frontend csr.read instruction executed."},
    coverage_point_info{coverage_point::frontend_system_fault, "frontend_system_fault", "System fault instruction executed."},
    coverage_point_info{coverage_point::system_fault_reserved_illegal, "system_fault_reserved_illegal", "A nonzero SYSTEM_FAULT reserved immediate is rejected as illegal."},
    coverage_point_info{coverage_point::loader_program_image_copy, "loader_program_image_copy", "loader program image local copy."},
    coverage_point_info{coverage_point::loader_argument_copy, "loader_argument_copy", "loader argument local copy."},
    coverage_point_info{coverage_point::loader_zero_argument_skip, "loader_zero_argument_skip", "loader zero-argument skip path."},
    coverage_point_info{coverage_point::control_loader_integration, "control_loader_integration", "control plane starts and observes the program loader."},
    coverage_point_info{coverage_point::program_flag_semantics, "program_flag_semantics", "descriptor flags gate terminal IRQs and fault snapshots and optionally clear performance counters before execution."},
    coverage_point_info{coverage_point::local_memory_program_read, "local_memory_program_read", "local program memory readback."},
    coverage_point_info{coverage_point::local_memory_data_read, "local_memory_data_read", "local data scratchpad readback."},
    coverage_point_info{coverage_point::local_memory_bounds_fault, "local_memory_bounds_fault", "local memory alignment or bounds fault."},
    coverage_point_info{coverage_point::local_memory_data_arbiter, "local_memory_data_arbiter", "data scratchpad arbiter handles loader/client write and host/client read contention."},
    coverage_point_info{coverage_point::control_local_memory_integration, "control_local_memory_integration", "control plane loads program and argument data into local memory."},
    coverage_point_info{coverage_point::frontend_system_exit, "frontend_system_exit", "reference frontend executes system.exit."},
    coverage_point_info{coverage_point::frontend_explicit_fault, "frontend_explicit_fault", "reference frontend executes system.fault."},
    coverage_point_info{coverage_point::completion_record_done, "completion_record_done", "publishes a complete successful completion record before MMIO DONE and IRQ."},
    coverage_point_info{coverage_point::completion_record_fault, "completion_record_fault", "publishes the precise program fault snapshot in the completion record."},
    coverage_point_info{coverage_point::completion_record_axi_error, "completion_record_axi_error", "converts a failed completion write response into an AXI_WRITE terminal fault."},
    coverage_point_info{coverage_point::completion_record_4k_split, "completion_record_4k_split", "completion record at a page tail is published as two AXI transactions."},
    coverage_point_info{coverage_point::frontend_illegal_instruction, "frontend_illegal_instruction", "reference frontend reports illegal instruction."},
    coverage_point_info{coverage_point::frontend_scalar_program, "frontend_scalar_program", "frontend executes scalar ALU, local load/store, and PC-relative loop control."},
    coverage_point_info{coverage_point::frontend_scalar_bounds_fault, "frontend_scalar_bounds_fault", "frontend rejects an invalid scalar local-memory access before issuing it."},
    coverage_point_info{coverage_point::frontend_debug_step, "frontend_debug_step", "frontend halts precisely, retires exactly one debug-step instruction, and resumes."},
    coverage_point_info{coverage_point::frontend_tile_program_done, "frontend_tile_program_done", "frontend tile launches a loaded program to completion."},
    coverage_point_info{coverage_point::frontend_dma_load_program, "frontend_dma_load_program", "frontend tile executes a DMA load program."},
    coverage_point_info{coverage_point::frontend_dma_store_program, "frontend_dma_store_program", "frontend tile executes a DMA store program."},
    coverage_point_info{coverage_point::frontend_sync_wait_dma, "frontend_sync_wait_dma", "frontend retires sync.wait_dma as an explicit DMA ordering point."},
    coverage_point_info{coverage_point::frontend_sync_fence_local, "frontend_sync_fence_local", "frontend retires sync.fence.local as a local-memory ordering point."},
    coverage_point_info{coverage_point::frontend_sync_fence_dma, "frontend_sync_fence_dma", "frontend retires sync.fence.dma as a DMA/local-memory ordering point."},
    coverage_point_info{coverage_point::frontend_vector_program, "frontend_vector_program", "frontend tile executes a vector program through the integrated vector engine."},
    coverage_point_info{coverage_point::frontend_predicate_program, "frontend_predicate_program", "frontend tile executes predicate load and masked vector operations from a program descriptor."},
    coverage_point_info{coverage_point::frontend_vector_helper_program, "frontend_vector_helper_program", "frontend tile executes select, gather, and reduction helpers from an ABI 3.0 program."},
    coverage_point_info{coverage_point::frontend_vector_extended_program, "frontend_vector_extended_program", "frontend tile matches the architectural simulator for zip, unzip, transpose, and saturating arithmetic in one program."},
    coverage_point_info{coverage_point::frontend_quant_program, "frontend_quant_program", "frontend tile executes metadata-owned requantization from an ABI 3.0 program."},
    coverage_point_info{coverage_point::frontend_vector_fault, "frontend_vector_fault", "frontend propagates a vector-engine fault precisely."},
    coverage_point_info{coverage_point::frontend_matrix_program, "frontend_matrix_program", "frontend tile executes a matrix micro-op program through the integrated B-weight-stationary engine."},
    coverage_point_info{coverage_point::product_top_program, "product_top_program", "product pin boundary loads and executes an ABI 3.0 program."},
    coverage_point_info{coverage_point::product_top_completion_ordering, "product_top_completion_ordering", "product top withholds DONE and IRQ until the completion-record AXI response is accepted."},
    coverage_point_info{coverage_point::engine_data_arbiter, "engine_data_arbiter", "DMA and vector engines share the scratchpad client port through interface-native arbitration."},
    coverage_point_info{coverage_point::dma_load_success, "dma_load_success", "frontend-issued DMA load writes local scratchpad."},
    coverage_point_info{coverage_point::dma_backpressure, "dma_backpressure", "DMA load honors local write backpressure."},
    coverage_point_info{coverage_point::dma_store_success, "dma_store_success", "frontend-issued DMA store writes system memory."},
    coverage_point_info{coverage_point::dma_bounds_fault, "dma_bounds_fault", "DMA rejects invalid local scratchpad ranges."},
    coverage_point_info{coverage_point::dma_address_overflow_fault, "dma_address_overflow_fault", "DMA rejects transfers that wrap the 64-bit system address space."},
    coverage_point_info{coverage_point::dma_axi_fault, "dma_axi_fault", "DMA reports AXI read response faults."},
    coverage_point_info{coverage_point::dma_store_bresp_fault, "dma_store_bresp_fault", "DMA reports AXI write response faults."},
    coverage_point_info{coverage_point::dma_load_4k_split, "dma_load_4k_split", "DMA load splits before crossing a 4 KiB boundary."},
    coverage_point_info{coverage_point::dma_store_4k_split, "dma_store_4k_split", "DMA store splits before crossing a 4 KiB boundary."},
    coverage_point_info{coverage_point::vector_config, "vector_config", "vector engine accepts metadata-owned VL, element width, and signedness."},
    coverage_point_info{coverage_point::vector_load_store, "vector_load_store", "vector engine loads and stores configured-width lanes through local memory."},
    coverage_point_info{coverage_point::vector_alu, "vector_alu", "vector engine executes type-orthogonal add/sub/min/max."},
    coverage_point_info{coverage_point::vector_compare_shift, "vector_compare_shift", "vector engine executes configured-width compare and shift operations."},
    coverage_point_info{coverage_point::vector_narrow_elements, "vector_narrow_elements", "vector engine executes signed and unsigned i8/i16 operations with byte-masked stores."},
    coverage_point_info{coverage_point::vector_predicate, "vector_predicate", "vector engine executes ptrue, bit-packed predicate load, inactive-lane preservation, and masked stores."},
    coverage_point_info{coverage_point::vector_saturating_arithmetic, "vector_saturating_arithmetic", "signed and unsigned add/sub clamp to configured element bounds when saturation is enabled."},
    coverage_point_info{coverage_point::vector_select, "vector_select", "vector select uses predicate-true and predicate-false source lanes."},
    coverage_point_info{coverage_point::vector_permute, "vector_permute", "vector gather executes valid indices and faults atomically on an out-of-range active index."},
    coverage_point_info{coverage_point::vector_pack_unpack, "vector_pack_unpack", "zip and unzip helpers pack both vector halves and reconstruct both original vectors."},
    coverage_point_info{coverage_point::vector_transpose, "vector_transpose", "transpose4 helper performs an explicit row-major 4x4 in-register transpose."},
    coverage_point_info{coverage_point::vector_reduction, "vector_reduction", "vector sum/min/max reductions implement documented empty-predicate identities."},
    coverage_point_info{coverage_point::vector_requant, "vector_requant", "requantization implements nearest-even rounding, zero point, clamp, and command validation."},
    coverage_point_info{coverage_point::vector_faults, "vector_faults", "vector engine reports config, bounds, and illegal instruction faults."},
    coverage_point_info{coverage_point::matrix_engine_clear, "matrix_engine_clear", "matrix engine clears accumulator zero before a tile product."},
    coverage_point_info{coverage_point::matrix_engine_accumulate, "matrix_engine_accumulate", "matrix engine accumulates a later K tile into a valid accumulator."},
    coverage_point_info{coverage_point::matrix_engine_store, "matrix_engine_store", "matrix engine stores INT32 accumulator values through local memory."},
    coverage_point_info{coverage_point::matrix_engine_fault, "matrix_engine_fault", "matrix engine rejects invalid command shape or encoding."},
    coverage_point_info{coverage_point::matrix_constrained_random, "matrix_constrained_random", "matrix engine matches signed INT8 golden results for deterministic random shapes and padded strides."},
    coverage_point_info{coverage_point::matrix_tiled_program, "matrix_tiled_program", "Public runtime-generated multi-tile GEMM programs execute through loader, frontend, scratchpad, and matrix RTL."},
    coverage_point_info{coverage_point::vector_constrained_random, "vector_constrained_random", "Deterministic random vector programs match the C++ architectural simulator through the integrated RTL tile."},
    coverage_point_info{coverage_point::runtime_examples_rtl, "runtime_examples_rtl", "Public runtime example program images execute unchanged in both the architectural simulator and integrated RTL tile."},
};

std::string_view coverage_point_name(coverage_point point);

class test_run {
public:
    test_run(std::string_view test_name, int argc, char** argv);

    test_run(const test_run&) = delete;
    test_run& operator=(const test_run&) = delete;

    test_run(test_run&&) = delete;
    test_run& operator=(test_run&&) = delete;

    void observe(coverage_point point, bool verified);
    void observe(std::initializer_list<coverage_point> points, bool verified);
    [[nodiscard]] int finish(bool passed) const;

private:
    std::string test_name_;
    std::string sanitized_name_;
    std::filesystem::path coverage_root_;
    std::vector<coverage_point> hit_points_;
    std::vector<std::string> verilator_args_;
    std::vector<char*> verilator_argv_;
};

}  // namespace holon_npu_tb
