#pragma once

#include <array>
#include <cstdint>
#include <filesystem>
#include <initializer_list>
#include <string>
#include <string_view>
#include <vector>

namespace holon_npu_tb {

enum class coverage_point : std::uint16_t {
    smoke_basic,
    common_fifo,
    common_skid_buffer,
    common_register_slice,
    pe_weight_load,
    pe_masked_weight,
    pe_negative_operands,
    pe_int32_wrap,
    array_shape_1,
    array_shape_16,
    array_shape_mixed_tail,
    tiling_masks,
    tiling_buffers,
    tiling_masked_tail,
    tiling_schedule,
    axi_lite_aw_w_skew,
    control_done_irq,
    control_error_irq,
    control_soft_reset,
    dma_read_single_burst,
    dma_read_multi_burst,
    dma_read_alignment_error,
    dma_read_axi_error,
    dma_write_single_burst,
    dma_write_multi_burst,
    dma_write_alignment_error,
    dma_write_axi_error,
    descriptor_valid,
    descriptor_invalid_version,
    descriptor_invalid_size,
    descriptor_invalid_flags,
    descriptor_reserved_nonzero,
    descriptor_address_overflow,
    descriptor_fuzz,
    isa_class_frontend_control,
    isa_class_predicate,
    isa_class_vector_config,
    isa_class_vector_alu,
    isa_class_vector_memory,
    isa_class_vector_permute,
    isa_class_vector_reduction,
    isa_class_quantization,
    isa_class_matrix,
    isa_class_dma,
    isa_class_csr_debug,
    isa_class_sync,
    isa_class_system,
    v2_frontend_control_movi,
    v2_frontend_control_add,
    v2_frontend_control_addi,
    v2_frontend_control_load,
    v2_frontend_control_store,
    v2_frontend_control_beq,
    v2_frontend_control_bne,
    v2_predicate_ptrue,
    v2_predicate_load,
    v2_vector_config_set,
    v2_vector_load,
    v2_vector_store,
    v2_vector_alu_add,
    v2_vector_alu_sub,
    v2_vector_alu_min,
    v2_vector_alu_max,
    v2_vector_alu_eq,
    v2_vector_alu_lt,
    v2_vector_alu_shl,
    v2_vector_alu_srl,
    v2_vector_alu_sra,
    v2_vector_alu_select,
    v2_vector_permute_gather,
    v2_vector_permute_zip_lo,
    v2_vector_permute_zip_hi,
    v2_vector_permute_unzip_even,
    v2_vector_permute_unzip_odd,
    v2_vector_permute_transpose4,
    v2_vector_reduce_sum,
    v2_vector_reduce_min,
    v2_vector_reduce_max,
    v2_quantization_requantize,
    v2_matrix_gemm_program,
    v2_csr_debug_read,
    v2_frontend_system_fault,
    v2_loader_program_image_copy,
    v2_loader_argument_copy,
    v2_loader_zero_argument_skip,
    v2_control_loader_integration,
    v2_program_flag_semantics,
    v2_local_memory_program_read,
    v2_local_memory_data_read,
    v2_local_memory_bounds_fault,
    v2_local_memory_data_arbiter,
    v2_control_local_memory_integration,
    v2_frontend_system_exit,
    v2_frontend_explicit_fault,
    v2_completion_record_done,
    v2_completion_record_fault,
    v2_completion_record_axi_error,
    v2_frontend_illegal_instruction,
    v2_frontend_scalar_program,
    v2_frontend_scalar_bounds_fault,
    v2_frontend_debug_step,
    v2_frontend_tile_program_done,
    v2_frontend_dma_load_program,
    v2_frontend_dma_store_program,
    v2_frontend_sync_wait_dma,
    v2_frontend_sync_fence_local,
    v2_frontend_sync_fence_dma,
    v2_frontend_vector_program,
    v2_frontend_predicate_program,
    v2_frontend_vector_helper_program,
    v2_frontend_vector_extended_program,
    v2_frontend_quant_program,
    v2_frontend_vector_fault,
    v2_frontend_matrix_program,
    v2_product_top_program,
    v2_product_top_completion_ordering,
    v2_engine_data_arbiter,
    v2_dma_load_success,
    v2_dma_backpressure,
    v2_dma_store_success,
    v2_dma_bounds_fault,
    v2_dma_address_overflow_fault,
    v2_dma_axi_fault,
    v2_dma_store_bresp_fault,
    v2_vector_config,
    v2_vector_load_store,
    v2_vector_alu,
    v2_vector_compare_shift,
    v2_vector_narrow_elements,
    v2_vector_predicate,
    v2_vector_saturating_arithmetic,
    v2_vector_select,
    v2_vector_permute,
    v2_vector_pack_unpack,
    v2_vector_transpose,
    v2_vector_reduction,
    v2_vector_requant,
    v2_vector_faults,
    v2_matrix_engine_clear,
    v2_matrix_engine_accumulate,
    v2_matrix_engine_store,
    v2_matrix_engine_fault,
    v2_matrix_constrained_random,
    v2_matrix_tiled_program,
    v2_vector_constrained_random,
    v2_runtime_examples_rtl,
    gemm_shape_1,
    gemm_shape_lt16,
    gemm_shape_16,
    gemm_shape_16_tail,
    gemm_shape_multi_tile,
    gemm_tail_m,
    gemm_tail_n,
    gemm_tail_k,
    gemm_tail_mixed,
    gemm_shape_64,
    gemm_reset_in_flight,
    gemm_axi_read_error,
    gemm_axi_write_error,
    top_gemm_fixed,
    top_gemm_constrained_random,
    top_status_done,
    top_status_error,
    top_axil_write_skew,
    top_descriptor_read_error,
    top_gemm_read_error,
    top_gemm_write_error,
    top_soft_reset_in_flight,
};

struct coverage_point_info {
    coverage_point point;
    std::string_view name;
    std::string_view description;
};

inline constexpr std::array coverage_registry{
    coverage_point_info{coverage_point::smoke_basic, "smoke_basic", "Smoke test completed."},
    coverage_point_info{coverage_point::common_fifo, "common_fifo", "Common FIFO behavior."},
    coverage_point_info{coverage_point::common_skid_buffer, "common_skid_buffer", "Skid buffer behavior."},
    coverage_point_info{coverage_point::common_register_slice, "common_register_slice", "Register slice behavior."},
    coverage_point_info{coverage_point::pe_weight_load, "pe_weight_load", "PE B weight load path."},
    coverage_point_info{coverage_point::pe_masked_weight, "pe_masked_weight", "PE masked weight behavior."},
    coverage_point_info{coverage_point::pe_negative_operands, "pe_negative_operands", "Signed negative PE operands."},
    coverage_point_info{coverage_point::pe_int32_wrap, "pe_int32_wrap", "INT32 wraparound arithmetic."},
    coverage_point_info{coverage_point::array_shape_1, "array_shape_1", "1x1x1 array shape."},
    coverage_point_info{coverage_point::array_shape_16, "array_shape_16", "16x16x16 array shape."},
    coverage_point_info{coverage_point::array_shape_mixed_tail, "array_shape_mixed_tail", "Mixed-tail array shape."},
    coverage_point_info{coverage_point::tiling_masks, "tiling_masks", "Tile mask generation."},
    coverage_point_info{coverage_point::tiling_buffers, "tiling_buffers", "Reusable tile buffers."},
    coverage_point_info{coverage_point::tiling_masked_tail, "tiling_masked_tail", "Masked tail compute path."},
    coverage_point_info{coverage_point::tiling_schedule, "tiling_schedule", "Tiling schedule progression."},
    coverage_point_info{coverage_point::axi_lite_aw_w_skew, "axi_lite_aw_w_skew", "AXI-Lite AW/W skew."},
    coverage_point_info{coverage_point::control_done_irq, "control_done_irq", "Control done IRQ path."},
    coverage_point_info{coverage_point::control_error_irq, "control_error_irq", "Control error IRQ path."},
    coverage_point_info{coverage_point::control_soft_reset, "control_soft_reset", "Control soft reset path."},
    coverage_point_info{coverage_point::dma_read_single_burst, "dma_read_single_burst", "Read DMA single burst."},
    coverage_point_info{coverage_point::dma_read_multi_burst, "dma_read_multi_burst", "Read DMA multi-burst transfer."},
    coverage_point_info{coverage_point::dma_read_alignment_error, "dma_read_alignment_error", "Read DMA alignment rejection."},
    coverage_point_info{coverage_point::dma_read_axi_error, "dma_read_axi_error", "Read DMA AXI error."},
    coverage_point_info{coverage_point::dma_write_single_burst, "dma_write_single_burst", "Write DMA single burst."},
    coverage_point_info{coverage_point::dma_write_multi_burst, "dma_write_multi_burst", "Write DMA multi-burst transfer."},
    coverage_point_info{coverage_point::dma_write_alignment_error, "dma_write_alignment_error", "Write DMA alignment rejection."},
    coverage_point_info{coverage_point::dma_write_axi_error, "dma_write_axi_error", "Write DMA AXI error."},
    coverage_point_info{coverage_point::descriptor_valid, "descriptor_valid", "Valid descriptor issue."},
    coverage_point_info{coverage_point::descriptor_invalid_version, "descriptor_invalid_version", "Invalid descriptor version."},
    coverage_point_info{coverage_point::descriptor_invalid_size, "descriptor_invalid_size", "Invalid descriptor size."},
    coverage_point_info{coverage_point::descriptor_invalid_flags, "descriptor_invalid_flags", "Invalid descriptor flags."},
    coverage_point_info{coverage_point::descriptor_reserved_nonzero, "descriptor_reserved_nonzero", "Reserved descriptor fields."},
    coverage_point_info{coverage_point::descriptor_address_overflow, "descriptor_address_overflow", "Descriptor and referenced system-memory ranges cannot wrap the 64-bit address space."},
    coverage_point_info{coverage_point::descriptor_fuzz, "descriptor_fuzz", "Descriptor fuzz cases."},
    coverage_point_info{coverage_point::isa_class_frontend_control, "isa_class_frontend_control", "Holon frontend-control ISA class executed."},
    coverage_point_info{coverage_point::isa_class_predicate, "isa_class_predicate", "Holon predicate ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_config, "isa_class_vector_config", "Holon vector-config ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_alu, "isa_class_vector_alu", "Holon vector-ALU ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_memory, "isa_class_vector_memory", "Holon vector-memory ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_permute, "isa_class_vector_permute", "Holon vector-permute ISA class executed."},
    coverage_point_info{coverage_point::isa_class_vector_reduction, "isa_class_vector_reduction", "Holon vector-reduction ISA class executed."},
    coverage_point_info{coverage_point::isa_class_quantization, "isa_class_quantization", "Holon quantization ISA class executed."},
    coverage_point_info{coverage_point::isa_class_matrix, "isa_class_matrix", "Holon matrix ISA class executed."},
    coverage_point_info{coverage_point::isa_class_dma, "isa_class_dma", "Holon DMA ISA class executed."},
    coverage_point_info{coverage_point::isa_class_csr_debug, "isa_class_csr_debug", "Holon CSR/debug ISA class executed."},
    coverage_point_info{coverage_point::isa_class_sync, "isa_class_sync", "Holon synchronization ISA class executed."},
    coverage_point_info{coverage_point::isa_class_system, "isa_class_system", "Holon system ISA class executed."},
    coverage_point_info{coverage_point::v2_frontend_control_movi, "v2_frontend_control_movi", "Frontend movi instruction executed."},
    coverage_point_info{coverage_point::v2_frontend_control_add, "v2_frontend_control_add", "Frontend add instruction executed."},
    coverage_point_info{coverage_point::v2_frontend_control_addi, "v2_frontend_control_addi", "Frontend addi instruction executed."},
    coverage_point_info{coverage_point::v2_frontend_control_load, "v2_frontend_control_load", "Frontend local load instruction executed."},
    coverage_point_info{coverage_point::v2_frontend_control_store, "v2_frontend_control_store", "Frontend local store instruction executed."},
    coverage_point_info{coverage_point::v2_frontend_control_beq, "v2_frontend_control_beq", "Frontend equality branch executed."},
    coverage_point_info{coverage_point::v2_frontend_control_bne, "v2_frontend_control_bne", "Frontend inequality branch executed."},
    coverage_point_info{coverage_point::v2_predicate_ptrue, "v2_predicate_ptrue", "Predicate ptrue instruction executed."},
    coverage_point_info{coverage_point::v2_predicate_load, "v2_predicate_load", "Predicate load instruction executed."},
    coverage_point_info{coverage_point::v2_vector_config_set, "v2_vector_config_set", "Vector configuration instruction executed."},
    coverage_point_info{coverage_point::v2_vector_load, "v2_vector_load", "Vector local load instruction executed."},
    coverage_point_info{coverage_point::v2_vector_store, "v2_vector_store", "Vector local store instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_add, "v2_vector_alu_add", "Vector add instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_sub, "v2_vector_alu_sub", "Vector subtract instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_min, "v2_vector_alu_min", "Vector minimum instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_max, "v2_vector_alu_max", "Vector maximum instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_eq, "v2_vector_alu_eq", "Vector equality instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_lt, "v2_vector_alu_lt", "Vector less-than instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_shl, "v2_vector_alu_shl", "Vector shift-left instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_srl, "v2_vector_alu_srl", "Vector logical shift-right instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_sra, "v2_vector_alu_sra", "Vector arithmetic shift-right instruction executed."},
    coverage_point_info{coverage_point::v2_vector_alu_select, "v2_vector_alu_select", "Vector select instruction executed."},
    coverage_point_info{coverage_point::v2_vector_permute_gather, "v2_vector_permute_gather", "Vector gather instruction executed."},
    coverage_point_info{coverage_point::v2_vector_permute_zip_lo, "v2_vector_permute_zip_lo", "Vector zip.lo instruction executed."},
    coverage_point_info{coverage_point::v2_vector_permute_zip_hi, "v2_vector_permute_zip_hi", "Vector zip.hi instruction executed."},
    coverage_point_info{coverage_point::v2_vector_permute_unzip_even, "v2_vector_permute_unzip_even", "Vector unzip.even instruction executed."},
    coverage_point_info{coverage_point::v2_vector_permute_unzip_odd, "v2_vector_permute_unzip_odd", "Vector unzip.odd instruction executed."},
    coverage_point_info{coverage_point::v2_vector_permute_transpose4, "v2_vector_permute_transpose4", "Vector transpose4 instruction executed."},
    coverage_point_info{coverage_point::v2_vector_reduce_sum, "v2_vector_reduce_sum", "Vector sum reduction executed."},
    coverage_point_info{coverage_point::v2_vector_reduce_min, "v2_vector_reduce_min", "Vector minimum reduction executed."},
    coverage_point_info{coverage_point::v2_vector_reduce_max, "v2_vector_reduce_max", "Vector maximum reduction executed."},
    coverage_point_info{coverage_point::v2_quantization_requantize, "v2_quantization_requantize", "Vector requantization instruction executed."},
    coverage_point_info{coverage_point::v2_matrix_gemm_program, "v2_matrix_gemm_program", "Matrix GEMM tile instruction executed."},
    coverage_point_info{coverage_point::v2_csr_debug_read, "v2_csr_debug_read", "Frontend csr.read instruction executed."},
    coverage_point_info{coverage_point::v2_frontend_system_fault, "v2_frontend_system_fault", "System fault instruction executed."},
    coverage_point_info{coverage_point::v2_loader_program_image_copy, "v2_loader_program_image_copy", "V2 loader program image local copy."},
    coverage_point_info{coverage_point::v2_loader_argument_copy, "v2_loader_argument_copy", "V2 loader argument local copy."},
    coverage_point_info{coverage_point::v2_loader_zero_argument_skip, "v2_loader_zero_argument_skip", "V2 loader zero-argument skip path."},
    coverage_point_info{coverage_point::v2_control_loader_integration, "v2_control_loader_integration", "V2 control plane starts and observes the program loader."},
    coverage_point_info{coverage_point::v2_program_flag_semantics, "v2_program_flag_semantics", "V2 descriptor flags gate terminal IRQs and fault snapshots and optionally clear performance counters before execution."},
    coverage_point_info{coverage_point::v2_local_memory_program_read, "v2_local_memory_program_read", "V2 local program memory readback."},
    coverage_point_info{coverage_point::v2_local_memory_data_read, "v2_local_memory_data_read", "V2 local data scratchpad readback."},
    coverage_point_info{coverage_point::v2_local_memory_bounds_fault, "v2_local_memory_bounds_fault", "V2 local memory alignment or bounds fault."},
    coverage_point_info{coverage_point::v2_local_memory_data_arbiter, "v2_local_memory_data_arbiter", "V2 data scratchpad arbiter handles loader/client write and host/client read contention."},
    coverage_point_info{coverage_point::v2_control_local_memory_integration, "v2_control_local_memory_integration", "V2 control plane loads program and argument data into local memory."},
    coverage_point_info{coverage_point::v2_frontend_system_exit, "v2_frontend_system_exit", "V2 reference frontend executes system.exit."},
    coverage_point_info{coverage_point::v2_frontend_explicit_fault, "v2_frontend_explicit_fault", "V2 reference frontend executes system.fault."},
    coverage_point_info{coverage_point::v2_completion_record_done, "v2_completion_record_done", "V2 publishes a complete successful completion record before MMIO DONE and IRQ."},
    coverage_point_info{coverage_point::v2_completion_record_fault, "v2_completion_record_fault", "V2 publishes the precise program fault snapshot in the completion record."},
    coverage_point_info{coverage_point::v2_completion_record_axi_error, "v2_completion_record_axi_error", "V2 converts a failed completion write response into an AXI_WRITE terminal fault."},
    coverage_point_info{coverage_point::v2_frontend_illegal_instruction, "v2_frontend_illegal_instruction", "V2 reference frontend reports illegal instruction."},
    coverage_point_info{coverage_point::v2_frontend_scalar_program, "v2_frontend_scalar_program", "V2 frontend executes scalar ALU, local load/store, and PC-relative loop control."},
    coverage_point_info{coverage_point::v2_frontend_scalar_bounds_fault, "v2_frontend_scalar_bounds_fault", "V2 frontend rejects an invalid scalar local-memory access before issuing it."},
    coverage_point_info{coverage_point::v2_frontend_debug_step, "v2_frontend_debug_step", "V2 frontend halts precisely, retires exactly one debug-step instruction, and resumes."},
    coverage_point_info{coverage_point::v2_frontend_tile_program_done, "v2_frontend_tile_program_done", "V2 frontend tile launches a loaded program to completion."},
    coverage_point_info{coverage_point::v2_frontend_dma_load_program, "v2_frontend_dma_load_program", "V2 frontend tile executes a DMA load program."},
    coverage_point_info{coverage_point::v2_frontend_dma_store_program, "v2_frontend_dma_store_program", "V2 frontend tile executes a DMA store program."},
    coverage_point_info{coverage_point::v2_frontend_sync_wait_dma, "v2_frontend_sync_wait_dma", "V2 frontend retires sync.wait_dma as an explicit DMA ordering point."},
    coverage_point_info{coverage_point::v2_frontend_sync_fence_local, "v2_frontend_sync_fence_local", "V2 frontend retires sync.fence.local as a local-memory ordering point."},
    coverage_point_info{coverage_point::v2_frontend_sync_fence_dma, "v2_frontend_sync_fence_dma", "V2 frontend retires sync.fence.dma as a DMA/local-memory ordering point."},
    coverage_point_info{coverage_point::v2_frontend_vector_program, "v2_frontend_vector_program", "V2 frontend tile executes a vector program through the integrated vector engine."},
    coverage_point_info{coverage_point::v2_frontend_predicate_program, "v2_frontend_predicate_program", "V2 frontend tile executes predicate load and masked vector operations from a program descriptor."},
    coverage_point_info{coverage_point::v2_frontend_vector_helper_program, "v2_frontend_vector_helper_program", "V2 frontend tile executes select, gather, and reduction helpers from an ABI 3.0 program."},
    coverage_point_info{coverage_point::v2_frontend_vector_extended_program, "v2_frontend_vector_extended_program", "V2 frontend tile matches the architectural simulator for zip, unzip, transpose, and saturating arithmetic in one program."},
    coverage_point_info{coverage_point::v2_frontend_quant_program, "v2_frontend_quant_program", "V2 frontend tile executes metadata-owned requantization from an ABI 3.0 program."},
    coverage_point_info{coverage_point::v2_frontend_vector_fault, "v2_frontend_vector_fault", "V2 frontend propagates a vector-engine fault precisely."},
    coverage_point_info{coverage_point::v2_frontend_matrix_program, "v2_frontend_matrix_program", "V2 frontend tile executes a matrix micro-op program through the integrated B-weight-stationary engine."},
    coverage_point_info{coverage_point::v2_product_top_program, "v2_product_top_program", "V2 product pin boundary loads and executes an ABI 3.0 program."},
    coverage_point_info{coverage_point::v2_product_top_completion_ordering, "v2_product_top_completion_ordering", "V2 product top withholds DONE and IRQ until the completion-record AXI response is accepted."},
    coverage_point_info{coverage_point::v2_engine_data_arbiter, "v2_engine_data_arbiter", "V2 DMA and vector engines share the scratchpad client port through interface-native arbitration."},
    coverage_point_info{coverage_point::v2_dma_load_success, "v2_dma_load_success", "V2 frontend-issued DMA load writes local scratchpad."},
    coverage_point_info{coverage_point::v2_dma_backpressure, "v2_dma_backpressure", "V2 DMA load honors local write backpressure."},
    coverage_point_info{coverage_point::v2_dma_store_success, "v2_dma_store_success", "V2 frontend-issued DMA store writes system memory."},
    coverage_point_info{coverage_point::v2_dma_bounds_fault, "v2_dma_bounds_fault", "V2 DMA rejects invalid local scratchpad ranges."},
    coverage_point_info{coverage_point::v2_dma_address_overflow_fault, "v2_dma_address_overflow_fault", "V2 DMA rejects transfers that wrap the 64-bit system address space."},
    coverage_point_info{coverage_point::v2_dma_axi_fault, "v2_dma_axi_fault", "V2 DMA reports AXI read response faults."},
    coverage_point_info{coverage_point::v2_dma_store_bresp_fault, "v2_dma_store_bresp_fault", "V2 DMA reports AXI write response faults."},
    coverage_point_info{coverage_point::v2_vector_config, "v2_vector_config", "V2 vector engine accepts metadata-owned VL, element width, and signedness."},
    coverage_point_info{coverage_point::v2_vector_load_store, "v2_vector_load_store", "V2 vector engine loads and stores configured-width lanes through local memory."},
    coverage_point_info{coverage_point::v2_vector_alu, "v2_vector_alu", "V2 vector engine executes type-orthogonal add/sub/min/max."},
    coverage_point_info{coverage_point::v2_vector_compare_shift, "v2_vector_compare_shift", "V2 vector engine executes configured-width compare and shift operations."},
    coverage_point_info{coverage_point::v2_vector_narrow_elements, "v2_vector_narrow_elements", "V2 vector engine executes signed and unsigned i8/i16 operations with byte-masked stores."},
    coverage_point_info{coverage_point::v2_vector_predicate, "v2_vector_predicate", "V2 vector engine executes ptrue, bit-packed predicate load, inactive-lane preservation, and masked stores."},
    coverage_point_info{coverage_point::v2_vector_saturating_arithmetic, "v2_vector_saturating_arithmetic", "V2 signed and unsigned add/sub clamp to configured element bounds when saturation is enabled."},
    coverage_point_info{coverage_point::v2_vector_select, "v2_vector_select", "V2 vector select uses predicate-true and predicate-false source lanes."},
    coverage_point_info{coverage_point::v2_vector_permute, "v2_vector_permute", "V2 vector gather executes valid indices and faults atomically on an out-of-range active index."},
    coverage_point_info{coverage_point::v2_vector_pack_unpack, "v2_vector_pack_unpack", "V2 zip and unzip helpers pack both vector halves and reconstruct both original vectors."},
    coverage_point_info{coverage_point::v2_vector_transpose, "v2_vector_transpose", "V2 transpose4 helper performs an explicit row-major 4x4 in-register transpose."},
    coverage_point_info{coverage_point::v2_vector_reduction, "v2_vector_reduction", "V2 vector sum/min/max reductions implement documented empty-predicate identities."},
    coverage_point_info{coverage_point::v2_vector_requant, "v2_vector_requant", "V2 requantization implements nearest-even rounding, zero point, clamp, and command validation."},
    coverage_point_info{coverage_point::v2_vector_faults, "v2_vector_faults", "V2 vector engine reports config, bounds, and illegal instruction faults."},
    coverage_point_info{coverage_point::v2_matrix_engine_clear, "v2_matrix_engine_clear", "V2 matrix engine clears accumulator zero before a tile product."},
    coverage_point_info{coverage_point::v2_matrix_engine_accumulate, "v2_matrix_engine_accumulate", "V2 matrix engine accumulates a later K tile into a valid accumulator."},
    coverage_point_info{coverage_point::v2_matrix_engine_store, "v2_matrix_engine_store", "V2 matrix engine stores INT32 accumulator values through local memory."},
    coverage_point_info{coverage_point::v2_matrix_engine_fault, "v2_matrix_engine_fault", "V2 matrix engine rejects invalid command shape or encoding."},
    coverage_point_info{coverage_point::v2_matrix_constrained_random, "v2_matrix_constrained_random", "V2 matrix engine matches signed INT8 golden results for deterministic random shapes and padded strides."},
    coverage_point_info{coverage_point::v2_matrix_tiled_program, "v2_matrix_tiled_program", "Public runtime-generated multi-tile GEMM programs execute through loader, frontend, scratchpad, and matrix RTL."},
    coverage_point_info{coverage_point::v2_vector_constrained_random, "v2_vector_constrained_random", "Deterministic random vector programs match the C++ architectural simulator through the integrated RTL tile."},
    coverage_point_info{coverage_point::v2_runtime_examples_rtl, "v2_runtime_examples_rtl", "Public runtime example program images execute unchanged in both the architectural simulator and integrated RTL tile."},
    coverage_point_info{coverage_point::gemm_shape_1, "gemm_shape_1", "GEMM 1-sized shape."},
    coverage_point_info{coverage_point::gemm_shape_lt16, "gemm_shape_lt16", "GEMM sub-16 shape."},
    coverage_point_info{coverage_point::gemm_shape_16, "gemm_shape_16", "GEMM exact 16 tile."},
    coverage_point_info{coverage_point::gemm_shape_16_tail, "gemm_shape_16_tail", "GEMM 16 plus tail shape."},
    coverage_point_info{coverage_point::gemm_shape_multi_tile, "gemm_shape_multi_tile", "GEMM multi-tile shape."},
    coverage_point_info{coverage_point::gemm_tail_m, "gemm_tail_m", "GEMM M tail."},
    coverage_point_info{coverage_point::gemm_tail_n, "gemm_tail_n", "GEMM N tail."},
    coverage_point_info{coverage_point::gemm_tail_k, "gemm_tail_k", "GEMM K tail."},
    coverage_point_info{coverage_point::gemm_tail_mixed, "gemm_tail_mixed", "GEMM mixed tail."},
    coverage_point_info{coverage_point::gemm_shape_64, "gemm_shape_64", "GEMM 64-sized anchor."},
    coverage_point_info{coverage_point::gemm_reset_in_flight, "gemm_reset_in_flight", "GEMM reset while active."},
    coverage_point_info{coverage_point::gemm_axi_read_error, "gemm_axi_read_error", "GEMM AXI read error."},
    coverage_point_info{coverage_point::gemm_axi_write_error, "gemm_axi_write_error", "GEMM AXI write error."},
    coverage_point_info{coverage_point::top_gemm_fixed, "top_gemm_fixed", "Top fixed GEMM cases."},
    coverage_point_info{coverage_point::top_gemm_constrained_random, "top_gemm_constrained_random", "Top random GEMM cases."},
    coverage_point_info{coverage_point::top_status_done, "top_status_done", "Top done status path."},
    coverage_point_info{coverage_point::top_status_error, "top_status_error", "Top error status path."},
    coverage_point_info{coverage_point::top_axil_write_skew, "top_axil_write_skew", "Top AXI-Lite write skew."},
    coverage_point_info{coverage_point::top_descriptor_read_error, "top_descriptor_read_error", "Top descriptor read error."},
    coverage_point_info{coverage_point::top_gemm_read_error, "top_gemm_read_error", "Top GEMM read error."},
    coverage_point_info{coverage_point::top_gemm_write_error, "top_gemm_write_error", "Top GEMM write error."},
    coverage_point_info{coverage_point::top_soft_reset_in_flight, "top_soft_reset_in_flight", "Top soft reset while active."},
};

std::string_view coverage_point_name(coverage_point point);

class test_run {
public:
    test_run(std::string_view test_name, int argc, char** argv);

    test_run(const test_run&) = delete;
    test_run& operator=(const test_run&) = delete;

    test_run(test_run&&) = delete;
    test_run& operator=(test_run&&) = delete;

    void cover(std::initializer_list<coverage_point> points);
    [[nodiscard]] int finish(bool passed) const;

private:
    std::string test_name_;
    std::string sanitized_name_;
    std::filesystem::path coverage_root_;
    std::vector<coverage_point> hit_points_;
    std::vector<std::string> verilator_args_;
    std::vector<char*> verilator_argv_;
};

}  // namespace holon_npu_tb
