// Generated from spec/holon_npu_isa.json; do not edit.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace holon_npu::semantic::instruction {

enum class npu_type : std::uint8_t {
    i8 = 0,
    u8 = 1,
    i16 = 2,
    u16 = 3,
    i32 = 4,
    u32 = 5,
    f32 = 6,
};
inline constexpr std::array npu_type_names{
    std::string_view{"i8"},
    std::string_view{"u8"},
    std::string_view{"i16"},
    std::string_view{"u16"},
    std::string_view{"i32"},
    std::string_view{"u32"},
    std::string_view{"f32"},
};
enum class mask_policy : std::uint8_t {
    merge = 0,
    zero = 1,
};
inline constexpr std::array mask_policy_names{
    std::string_view{"merge"},
    std::string_view{"zero"},
};
enum class rounding_mode : std::uint8_t {
    rne = 0,
    rtz = 1,
    rdn = 2,
    rup = 3,
};
inline constexpr std::array rounding_mode_names{
    std::string_view{"rne"},
    std::string_view{"rtz"},
    std::string_view{"rdn"},
    std::string_view{"rup"},
};
enum class resource_capacity : std::uint8_t {
    vector_bytes = 0,
    matrix_rows = 1,
    matrix_cols = 2,
    tile_bytes = 3,
};
inline constexpr std::array resource_capacity_names{
    std::string_view{"vector_bytes"},
    std::string_view{"matrix_rows"},
    std::string_view{"matrix_cols"},
    std::string_view{"tile_bytes"},
};
enum class npu_trap : std::uint8_t {
    invalid_operand = 24,
};
enum class npu_kind : std::uint8_t {
    scalar,
    vector,
    predicate,
    tile,
    view,
    element,
    policy,
    rounding,
    displacement,
    scale,
    capability,
};
enum class npu_role : std::uint8_t {
    rd,
    avl,
    vl,
    base,
    end,
    stride,
    index,
    seed,
    value,
    rows,
    cols,
    row_stride,
    col_stride,
    dst,
    src,
    count,
    status,
    vd,
    va,
    vb,
    vc,
    indices,
    pd,
    pa,
    pb,
    pg,
    select,
    td,
    ta,
    tb,
    ts,
    view,
    type,
    peer_type,
    result_type,
    policy,
    rounding,
    offset,
    scale,
    selector,
};
inline constexpr unsigned npu_scalar_count = 32;
inline constexpr unsigned npu_vector_count = 32;
inline constexpr unsigned npu_predicate_count = 32;
inline constexpr unsigned npu_tile_count = 8;
inline constexpr unsigned npu_view_count = 16;
inline constexpr unsigned npu_max_operands = 10;
enum class npu_opcode : std::uint16_t {
    VSETL = 0x07c,
    VADD = 0x004,
    VSUB = 0x008,
    VMUL = 0x00c,
    VMULH = 0x06c,
    VMIN = 0x010,
    VMAX = 0x014,
    VDIV = 0x018,
    VSQRT = 0x01c,
    VFMA = 0x020,
    VAND = 0x024,
    VOR = 0x028,
    VXOR = 0x02c,
    VSHL = 0x030,
    VSHR = 0x034,
    VASHR = 0x038,
    VCONVERT = 0x03c,
    VCMPEQ = 0x040,
    VCMPLT = 0x044,
    VCMPLE = 0x048,
    VCMPNE = 0x04c,
    VSELECT = 0x050,
    VBROADCAST = 0x054,
    VEXTRACT = 0x058,
    VPERMUTE = 0x05c,
    VREDSUM = 0x060,
    VREDMIN = 0x064,
    VREDMAX = 0x068,
    VLD = 0x080,
    VST = 0x084,
    VLDS = 0x088,
    VSTS = 0x08c,
    VGATHER = 0x090,
    VSCATTER = 0x094,
    PTRUE = 0x100,
    PWHILELT = 0x104,
    PAND = 0x108,
    POR = 0x10c,
    PXOR = 0x110,
    PNOT = 0x114,
    PCOUNT = 0x118,
    PFIRST = 0x11c,
    PLD = 0x120,
    PST = 0x124,
    MVIEW = 0x001,
    MLOAD = 0x005,
    MCLEAR = 0x009,
    MDOT = 0x00d,
    MMACC = 0x011,
    MSTORE = 0x015,
    DLOAD = 0x002,
    DSTORE = 0x006,
    STOP = 0x00e,
    CAPS = 0x012,
};
struct npu_field {
    npu_role role; npu_kind kind;
    unsigned shift, width; std::string_view name;
};
struct npu_pattern {
    npu_opcode opcode; std::string_view name;
    std::uint64_t variable_mask; unsigned type_mask;
    unsigned count; std::array<npu_field, npu_max_operands> fields;
};
inline constexpr std::array npu_patterns{
    npu_pattern{npu_opcode::VSETL, "vsetl", 0x0007bc00003ff000ull, 0x7f, 4, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::avl, npu_kind::scalar, 17, 5, "avl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::peer_type, npu_kind::element, 47, 4, "peer_type"},
    }}},
    npu_pattern{npu_opcode::VADD, "vadd", 0x00007fff07fff000ull, 0x7f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VSUB, "vsub", 0x00007fff07fff000ull, 0x7f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VMUL, "vmul", 0x00007fff07fff000ull, 0x7f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VMULH, "vmulh", 0x00007fff07fff000ull, 0x3f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VMIN, "vmin", 0x00007fff07fff000ull, 0x7f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VMAX, "vmax", 0x00007fff07fff000ull, 0x7f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VDIV, "vdiv", 0x00007fff07fff000ull, 0x40, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VSQRT, "vsqrt", 0x00007fff003ff000ull, 0x40, 6, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VFMA, "vfma", 0x00007ffffffff000ull, 0x40, 8, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::vc, npu_kind::vector, 27, 5, "vc"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VAND, "vand", 0x00007fff07fff000ull, 0x3f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VOR, "vor", 0x00007fff07fff000ull, 0x3f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VXOR, "vxor", 0x00007fff07fff000ull, 0x3f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VSHL, "vshl", 0x00007fff07fff000ull, 0x3f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VSHR, "vshr", 0x00007fff07fff000ull, 0x3f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VASHR, "vashr", 0x00007fff07fff000ull, 0x15, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VCONVERT, "vconvert", 0x001fffff003ff000ull, 0x7f, 8, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
        {npu_role::result_type, npu_kind::element, 47, 4, "result_type"},
        {npu_role::rounding, npu_kind::rounding, 51, 2, "rounding"},
    }}},
    npu_pattern{npu_opcode::VCMPEQ, "vcmpeq", 0x00003fff07fff000ull, 0x7f, 6, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VCMPLT, "vcmplt", 0x00003fff07fff000ull, 0x7f, 6, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VCMPLE, "vcmple", 0x00003fff07fff000ull, 0x7f, 6, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VCMPNE, "vcmpne", 0x00003fff07fff000ull, 0x7f, 6, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VSELECT, "vselect", 0x00007ffffffff000ull, 0x7f, 8, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::vb, npu_kind::vector, 22, 5, "vb"},
        {npu_role::select, npu_kind::predicate, 27, 5, "select"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VBROADCAST, "vbroadcast", 0x00007fff003ff000ull, 0x7f, 6, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::value, npu_kind::scalar, 17, 5, "value"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VEXTRACT, "vextract", 0x00003fe007fff000ull, 0x7f, 5, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::index, npu_kind::scalar, 22, 5, "index"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VPERMUTE, "vpermute", 0x00007fff07fff000ull, 0x7f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::indices, npu_kind::vector, 22, 5, "indices"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
        {npu_role::policy, npu_kind::policy, 46, 1, "policy"},
    }}},
    npu_pattern{npu_opcode::VREDSUM, "vredsum", 0x00003fff07fff000ull, 0x7f, 6, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::seed, npu_kind::scalar, 22, 5, "seed"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VREDMIN, "vredmin", 0x00003fff07fff000ull, 0x7f, 6, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::seed, npu_kind::scalar, 22, 5, "seed"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VREDMAX, "vredmax", 0x00003fff07fff000ull, 0x7f, 6, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::va, npu_kind::vector, 17, 5, "va"},
        {npu_role::seed, npu_kind::scalar, 22, 5, "seed"},
        {npu_role::pg, npu_kind::predicate, 32, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::VLD, "vld", 0xfffff3fff83ff000ull, 0x7f, 7, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::pg, npu_kind::predicate, 27, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::type, npu_kind::element, 37, 4, "type"},
        {npu_role::policy, npu_kind::policy, 41, 1, "policy"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::VST, "vst", 0xfffff1fff83ff000ull, 0x7f, 6, {{
        {npu_role::va, npu_kind::vector, 12, 5, "va"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::pg, npu_kind::predicate, 27, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::type, npu_kind::element, 37, 4, "type"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::VLDS, "vlds", 0xfffff3fffffff000ull, 0x7f, 8, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::stride, npu_kind::scalar, 22, 5, "stride"},
        {npu_role::pg, npu_kind::predicate, 27, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::type, npu_kind::element, 37, 4, "type"},
        {npu_role::policy, npu_kind::policy, 41, 1, "policy"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::VSTS, "vsts", 0xfffff1fffffff000ull, 0x7f, 7, {{
        {npu_role::va, npu_kind::vector, 12, 5, "va"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::stride, npu_kind::scalar, 22, 5, "stride"},
        {npu_role::pg, npu_kind::predicate, 27, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::type, npu_kind::element, 37, 4, "type"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::VGATHER, "vgather", 0xfffffffffffff000ull, 0x7f, 9, {{
        {npu_role::vd, npu_kind::vector, 12, 5, "vd"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::indices, npu_kind::vector, 22, 5, "indices"},
        {npu_role::pg, npu_kind::predicate, 27, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::type, npu_kind::element, 37, 4, "type"},
        {npu_role::policy, npu_kind::policy, 41, 1, "policy"},
        {npu_role::scale, npu_kind::scale, 42, 2, "scale"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::VSCATTER, "vscatter", 0xfffffdfffffff000ull, 0x7f, 8, {{
        {npu_role::va, npu_kind::vector, 12, 5, "va"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::indices, npu_kind::vector, 22, 5, "indices"},
        {npu_role::pg, npu_kind::predicate, 27, 5, "pg"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::type, npu_kind::element, 37, 4, "type"},
        {npu_role::scale, npu_kind::scale, 42, 2, "scale"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::PTRUE, "ptrue", 0x000003e00001f000ull, 0x7f, 2, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::PWHILELT, "pwhilelt", 0x000003e007fff000ull, 0x7f, 4, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::end, npu_kind::scalar, 22, 5, "end"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::PAND, "pand", 0x000003e007fff000ull, 0x7f, 4, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::pa, npu_kind::predicate, 17, 5, "pa"},
        {npu_role::pb, npu_kind::predicate, 22, 5, "pb"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::POR, "por", 0x000003e007fff000ull, 0x7f, 4, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::pa, npu_kind::predicate, 17, 5, "pa"},
        {npu_role::pb, npu_kind::predicate, 22, 5, "pb"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::PXOR, "pxor", 0x000003e007fff000ull, 0x7f, 4, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::pa, npu_kind::predicate, 17, 5, "pa"},
        {npu_role::pb, npu_kind::predicate, 22, 5, "pb"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::PNOT, "pnot", 0x000003e0003ff000ull, 0x7f, 3, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::pa, npu_kind::predicate, 17, 5, "pa"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::PCOUNT, "pcount", 0x000003e0003ff000ull, 0x7f, 3, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::pa, npu_kind::predicate, 17, 5, "pa"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::PFIRST, "pfirst", 0x000003e0003ff000ull, 0x7f, 3, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::pa, npu_kind::predicate, 17, 5, "pa"},
        {npu_role::vl, npu_kind::scalar, 37, 5, "vl"},
    }}},
    npu_pattern{npu_opcode::PLD, "pld", 0xfffff01f003ff000ull, 0x7f, 4, {{
        {npu_role::pd, npu_kind::predicate, 12, 5, "pd"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::PST, "pst", 0xfffff01f003ff000ull, 0x7f, 4, {{
        {npu_role::pa, npu_kind::predicate, 12, 5, "pa"},
        {npu_role::base, npu_kind::scalar, 17, 5, "base"},
        {npu_role::vl, npu_kind::scalar, 32, 5, "vl"},
        {npu_role::offset, npu_kind::displacement, 44, 20, "offset"},
    }}},
    npu_pattern{npu_opcode::MVIEW, "mview", 0x00001ffffffff000ull, 0x7f, 7, {{
        {npu_role::view, npu_kind::view, 12, 4, "view"},
        {npu_role::base, npu_kind::scalar, 16, 5, "base"},
        {npu_role::rows, npu_kind::scalar, 21, 5, "rows"},
        {npu_role::cols, npu_kind::scalar, 26, 5, "cols"},
        {npu_role::row_stride, npu_kind::scalar, 31, 5, "row_stride"},
        {npu_role::col_stride, npu_kind::scalar, 36, 5, "col_stride"},
        {npu_role::type, npu_kind::element, 41, 4, "type"},
    }}},
    npu_pattern{npu_opcode::MLOAD, "mload", 0x000000000007f000ull, 0x7f, 2, {{
        {npu_role::td, npu_kind::tile, 12, 3, "td"},
        {npu_role::view, npu_kind::view, 15, 4, "view"},
    }}},
    npu_pattern{npu_opcode::MCLEAR, "mclear", 0x00003c0007fe7000ull, 0x7f, 4, {{
        {npu_role::td, npu_kind::tile, 12, 3, "td"},
        {npu_role::rows, npu_kind::scalar, 17, 5, "rows"},
        {npu_role::cols, npu_kind::scalar, 22, 5, "cols"},
        {npu_role::type, npu_kind::element, 42, 4, "type"},
    }}},
    npu_pattern{npu_opcode::MDOT, "mdot", 0x0000000001fff000ull, 0x70, 4, {{
        {npu_role::td, npu_kind::tile, 12, 3, "td"},
        {npu_role::ta, npu_kind::tile, 15, 3, "ta"},
        {npu_role::tb, npu_kind::tile, 18, 3, "tb"},
        {npu_role::type, npu_kind::element, 21, 4, "type"},
    }}},
    npu_pattern{npu_opcode::MMACC, "mmacc", 0x0000000001fff000ull, 0x70, 4, {{
        {npu_role::td, npu_kind::tile, 12, 3, "td"},
        {npu_role::ta, npu_kind::tile, 15, 3, "ta"},
        {npu_role::tb, npu_kind::tile, 18, 3, "tb"},
        {npu_role::type, npu_kind::element, 21, 4, "type"},
    }}},
    npu_pattern{npu_opcode::MSTORE, "mstore", 0x000000000007f000ull, 0x7f, 2, {{
        {npu_role::ts, npu_kind::tile, 12, 3, "ts"},
        {npu_role::view, npu_kind::view, 15, 4, "view"},
    }}},
    npu_pattern{npu_opcode::DLOAD, "dload", 0x0000000007fff000ull, 0x7f, 3, {{
        {npu_role::dst, npu_kind::scalar, 12, 5, "dst"},
        {npu_role::src, npu_kind::scalar, 17, 5, "src"},
        {npu_role::count, npu_kind::scalar, 22, 5, "count"},
    }}},
    npu_pattern{npu_opcode::DSTORE, "dstore", 0x0000000007fff000ull, 0x7f, 3, {{
        {npu_role::dst, npu_kind::scalar, 12, 5, "dst"},
        {npu_role::src, npu_kind::scalar, 17, 5, "src"},
        {npu_role::count, npu_kind::scalar, 22, 5, "count"},
    }}},
    npu_pattern{npu_opcode::STOP, "stop", 0x000000000001f000ull, 0x7f, 1, {{
        {npu_role::status, npu_kind::scalar, 12, 5, "status"},
    }}},
    npu_pattern{npu_opcode::CAPS, "caps", 0x000000000007f000ull, 0x7f, 2, {{
        {npu_role::rd, npu_kind::scalar, 12, 5, "rd"},
        {npu_role::selector, npu_kind::capability, 17, 2, "selector"},
    }}},
};

} // namespace holon_npu::semantic::instruction
